Repository BitsPleaseBr/bits-please, pull requests merged in 2018-07, with the labels that each got.

#21 Criação package "br.com.bitsplease.dao"e classe PacienteDao
  src/br/com/bitsplease/dao/PacienteDao.java
Labels: controller, novo recurso

#22 Diogo
  src/control/crypto/BCrypt.java
  src/control/crypto/PswdStorage.java
  src/controller/PswdStorage.java
  test/crypto/CryptoTest.java
Labels: alteração, controller, novo recurso

#25 Classe para conexão com BD
  Libs/mysql-connector-java-8.0.11.jar
  src/model/conexao/ConnectionFactory.java
  testes/control/CryptoTest.java
  testes/model/ConnectionTest.java
Labels: alteração, model, novo recurso

#26 UML project
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/novo-recurso-ideia.md
  .github/ISSUE_TEMPLATE/novo-recurso.md
  CODEOWNERS
  Libs/mysql-connector-java-8.0.11.jar
  Modelo BD/BDModel.mwb
  Modelo BD/BDModel.mwb.bak
  PULL_REQUEST_TEMPLATE.md
  README.md
  src/Interfaces/EPasswordField.java
  src/Interfaces/ETextField.java
  src/Interfaces/LblMouseListener.java
  src/Interfaces/Telas.java
  src/Interfaces/img/logo.png
  src/br/com/bitsplease/dao/PacienteDao.java
  src/classes/Paciente.java
  src/control/crypto/BCrypt.java
  src/control/crypto/PswdStorage.java
  src/model/conexao/ConnectionFactory.java
  testes/control/CryptoTest.java
  testes/model/ConnectionTest.java
Labels: novo recurso

#27 UML Project
  UMLdraw/TheWholePictureUntilNow.jpg
  UMLdraw/bitsplease.mdj
Labels: novo recurso

#32 Alterações na classe PacienteDao e PacienteBean
  src/control/bean/PacienteBean.java
  src/control/dao/PacienteDao.java
Labels: alteração

#33 AGORA TÁ INDO
  Modelo BD/BDModel.mwb
  Modelo BD/BDModel.mwb.bak
  src/br/com/bitsplease/dao/PacienteDao.java
  src/control/MainController.java
  src/control/MainValidator.java
  src/control/PswdStorage.java
  src/control/bean/PacienteBean.java
  src/control/crypto/BCrypt.java
  src/control/crypto/PswdStorage.java
  src/control/dao/PacienteDao.java
  src/interfaces/Tela.java
  src/interfaces/componentes/EPasswordField.java
  src/interfaces/componentes/ETextField.java
  src/interfaces/componentes/LblMouseListener.java
  src/interfaces/componentes/MainPanel.java
  src/interfaces/componentes/Popup.java
  src/interfaces/componentes/ScreenConfiguration.java
  src/interfaces/popups/PopupEsqueciSenha.java
  src/interfaces/telas/TelaConfirmarCadastro.java
  src/interfaces/telas/TelaInicio.java
  src/interfaces/telas/TelaLogin.java
  src/interfaces/telas/TelaPreCadastroPaciente.java
  src/model/conexao/ConnectionFactory.java
  testes/model/ConnectionTest.java
Labels: alteração, bug, controller, model, view

#35 Diogo
  Modelo BD/BDModel.mwb
  Modelo BD/BDModel.mwb.bak
  src/control/bean/PacienteBean.java
  src/control/dao/PacienteDao.java
  testes/control/DaoTests.java
Labels: alteração, bug, controller, model

#37 Pré-Cadastro completo
  UMLdraw/TheWholePictureUntilNow.jpg
  UMLdraw/bitsplease.mdj
  src/interfaces/telas/TelaConfirmarCadastro.java
  src/interfaces/telas/TelaPreCadastroPaciente.java
Labels: meta, novo recurso

#38 Criando pasta para website
  docs/index.html
Labels: novo recurso

#40 Nathan
  UMLdraw/TheWholePictureUntilNow.jpg
  UMLdraw/bitsplease.mdj
  WebContent/css/estilos.css
  WebContent/img/icon.png
  WebContent/img/key.png
  WebContent/img/logo.png
  WebContent/img/user.png
  WebContent/includes/modalConfirmar.jsp
  WebContent/includes/modalPaciente.jsp
  WebContent/includes/modalProfissional.jsp
  WebContent/includes/topo.jsp
  WebContent/index.html
  WebContent/index.jsp
  WebContent/js/funcoes.js
  src/control/bean/MedicoBean.java
  src/control/crypto/PswdStorage.java
  src/control/dao/PacienteDao.java
  src/interfaces/img/logo.jpg
  src/interfaces/telas/TelaConfirmarCadastro.java
  src/interfaces/telas/TelaLogin.java
  testes/control/CryptoTest.java
  testes/control/DaoTests.java
Labels: ideia, meta, novo recurso, view

#43 Melhor organização e amaração de pontas
  WebContent/_css/estilos.css
  WebContent/_img/icon.png
  WebContent/_img/key.png
  WebContent/_img/logo.png
  WebContent/_img/user.png
  WebContent/_js/funcoes.js
  WebContent/includes/modalPaciente.jsp
  WebContent/includes/topo.jsp
  WebContent/index.jsp
Labels: alteração, view

#51 Método de hash no cadastro
  src/interfaces/telas/TelaConfirmarCadastro.java
Labels: alteração, model, view

#53 Gus
  README.md
  WebContent/_css/estilos.css
  WebContent/_js/funcoes.js
  WebContent/includes/cadastro/cadastrarPaciente.jsp
  WebContent/includes/cadastro/cadastrarProfissional.jsp
  WebContent/includes/cadastro/modalConfirmar.jsp
  WebContent/includes/cadastro/modalPaciente.jsp
  WebContent/includes/cadastro/modalProfissional.jsp
  WebContent/index.jsp
  src/control/MainController.java
  src/control/MainValidator.java
  src/control/bean/PacienteBean.java
  src/control/crypto/BCrypt.java
  src/control/crypto/PswdStorage.java
  src/control/dao/PacienteDao.java
  src/control/validators/MainValidator.java
  src/interfaces/Tela.java
  src/interfaces/componentes/EPasswordField.java
  src/interfaces/componentes/ETextField.java
  src/interfaces/componentes/LblMouseListener.java
  src/interfaces/componentes/MainPanel.java
  src/interfaces/componentes/Popup.java
  src/interfaces/componentes/ScreenConfiguration.java
  src/interfaces/popups/PopupEsqueciSenha.java
  src/interfaces/telas/TelaConfirmarCadastro.java
  src/interfaces/telas/TelaInicio.java
  src/interfaces/telas/TelaLogin.java
  src/interfaces/telas/TelaPreCadastroPaciente.java
  src/model/bean/Bean.java
  src/model/bean/PacienteBean.java
  src/model/bean/ProfissionalBean.java
  src/model/bean/UserBean.java
  src/model/conexao/ConnectionFactory.java
  src/model/dao/Dao.java
  src/model/dao/PacienteDao.java
  src/model/dao/ProfissionalDao.java
  src/model/dao/UserDao.java
  src/model/info/Info.java
  src/model/info/PacienteInfo.java
  src/model/info/ProfissionalInfo.java
  src/model/info/UserInfo.java
  testes/control/BeanTests.java
  testes/control/DaoTests.java
  testes/model/ConnectionTest.java
Labels: alteração

#55 Cadastro finish
  .settings/org.eclipse.core.resources.prefs
  WebContent/_acoes/cadastrarPaciente.jsp
  WebContent/_acoes/cadastrarProfissional.jsp
  WebContent/_acoes/login.jsp
  WebContent/_css/estilos.css
  WebContent/_js/funcoes.js
  WebContent/includes/cadastro/modalConfirmar.jsp
  WebContent/includes/cadastro/modalPaciente.jsp
  WebContent/includes/cadastro/modalProfissional.jsp
  WebContent/includes/topo.jsp
  WebContent/index.jsp
Labels: alteração, view
