Repository BitsPleaseBr/bits-please, pull requests merged in 2018-08, with the labels that each got.

#64 Arrumando formatação de data nos cadastro
  WebContent/_js/funcoes.js
  WebContent/index.jsp
  src/control/extras/Arquivo.java
Labels: alteração, bug, model

#66 Diagramas
  UMLdraw/Diagrama de Casos de Uso.jpg
  UMLdraw/Diagrama de Casos de Uso.mdj
  UMLdraw/Diagrama de Classes.mdj
  UMLdraw/Diagrame de Classes.jpg
  UMLdraw/TheWholePictureUntilNow.jpg
Labels: UML, alteração, novo recurso

#65 Alteração de Infos e Beans
  WebContent/_acoes/cadastrarPaciente.jsp
  WebContent/_acoes/cadastrarProfissional.jsp
  src/control/validators/Parsers.java
  src/model/bean/Bean.java
  src/model/bean/EnderecoBean.java
  src/model/bean/MedicoBean.java
  src/model/bean/PacienteBean.java
  src/model/bean/TelefoneBean.java
  src/model/bean/UserBean.java
  src/model/bean/info/EnderecoInfo.java
  src/model/bean/info/Info.java
  src/model/bean/info/MedicoInfo.java
  src/model/bean/info/PacienteInfo.java
  src/model/bean/info/TelefoneInfo.java
  src/model/bean/info/UserInfo.java
  src/model/dao/Dao.java
  src/model/dao/PacienteDao.java
  src/model/dao/ProfissionalDao.java
  src/model/info/EnderecoInfo.java
  src/model/info/Info.java
  src/model/info/MedicoInfo.java
  src/model/info/PacienteInfo.java
  src/model/info/TelefoneInfo.java
  src/model/info/UserInfo.java
Labels: alteração, controller, model

#79 Atualizando códigos de cadastro
  .settings/.gitignore
  WebContent/_acoes/cadastrarPaciente.jsp
  WebContent/_acoes/cadastrarProfissional.jsp
  src/control/validators/Parsers.java
  src/model/bean/EnderecoBean.java
  src/model/bean/MedicoBean.java
  src/model/bean/PacienteBean.java
  src/model/bean/TelefoneBean.java
  src/model/bean/UserBean.java
  src/model/bean/info/EnderecoInfo.java
  src/model/bean/info/Tabela.java
  src/model/bean/info/TelefoneInfo.java
  src/model/bean/info/UserInfo.java
  src/model/dao/Dao.java
  src/model/dao/MedicoDao.java
  src/model/dao/PacienteDao.java
  src/model/dao/ProfissionalDao.java
  src/model/dao/StatementFactory.java
  src/model/dao/UserDao.java
Labels: alteração, bug, novo recurso

#80 Validador de Cpf
  WebContent/_js/funcoes.js
  WebContent/includes/cadastro/modalPaciente.jsp
  WebContent/includes/cadastro/modalProfissional.jsp
Labels: alteração, view

#81 Verificação de CPF e Email
  WebContent/_acoes/verificarCPF.jsp
  WebContent/_acoes/verificarEmail.jsp
  WebContent/_js/funcoes.js
  WebContent/includes/cadastro/modalPaciente.jsp
  WebContent/includes/cadastro/modalProfissional.jsp
  WebContent/index.jsp
Labels: alteração, bug, mandei muito

#82 Gus
  .settings/.gitignore
  .settings/org.eclipse.core.resources.prefs
Labels: bug, meta
